# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
variables:
- group: CricketCreationsVariableGroup

trigger:
- main

stages:
- stage: Build
  displayName: 'Build Cricket Creations Server and Client'
  jobs: 
  - job: Build 

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '14.x'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          git submodule update --init --recursive

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: MSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArchitecture: 'x64'
        msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployCricketCreations
  displayName: 'Deploy Cricket Creations Web App'
  jobs:
    - job: DeployCricketCreations
      pool:
        vmImage: 'windows-latest'
      steps: 
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'CricketCreationsSubscription'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo groups
              az group list
              echo -----------------
              echo resources in centralus
              az resource list --location centralus
              echo -----------------
              az group list
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'CricketCreationsSubscription'
            appType: 'webApp'
            WebAppName: '$(WEB_APP_NAME)'
            deployToSlotOrASE: true
            ResourceGroupName: '$(RESOURCE_GROUP_NAME)'
            SlotName: 'staging'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        - task: AzureAppServiceSettings@1
          inputs:
            azureSubscription: 'CricketCreationsSubscription'
            appName: '$(WEB_APP_NAME)'
            resourceGroupName: '$(RESOURCE_GROUP_NAME)'
            connectionStrings: |
              [
                {
                  "name": "DbConnection",
                  "value": "Server=tcp:$(SQL_SERVER_NAME).database.windows.net,1433;Initial Catalog=cricket-creations-test-db;Persist Security Info=False;User ID=$(USER_NAME);Password=$(PASSWORD);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;",
                  "type": "SqlAzure",
                  "slotSetting": true
                }
              ]
        